/* eslint-disable max-len */
export const recipe = {
  id: 643809,
  title: "Fried String Cheese Sticks",
  image: "https://spoonacular.com/recipeImages/643809-556x370.jpg",
  extendedIngredients: [
    {
      id: 98970,
      aisle: "Cheese",
      image: "string-cheese.png",
      consistency: "SOLID",
      name: "individual string cheese sticks",
      nameClean: "string cheese",
      original: "4 individual string cheese sticks",
      originalName: "individual string cheese sticks",
      amount: 4,
      unit: "",
      meta: [],
      measures: {
        us: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 20081,
      aisle: "Baking",
      image: "flour.png",
      consistency: "SOLID",
      name: "flour",
      nameClean: "wheat flour",
      original: "1/4 cup flour",
      originalName: "flour",
      amount: 0.25,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 31.25,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "SOLID",
      name: "egg +2 water",
      nameClean: "egg",
      original: "1 tablespoon egg +2 water (egg wash)",
      originalName: "egg +2 water (egg wash)",
      amount: 1,
      unit: "tablespoon",
      meta: ["(egg wash)"],
      measures: {
        us: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 18376,
      aisle: "Bakery/Bread;Oil, Vinegar, Salad Dressing;Baking",
      image: "breadcrumbs.jpg",
      consistency: "SOLID",
      name: "seasoned bread crumbs",
      nameClean: "seasoned breadcrumbs",
      original: "1/2 cup Italian seasoned bread crumbs",
      originalName: "Italian seasoned bread crumbs",
      amount: 0.5,
      unit: "cup",
      meta: ["italian"],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 60,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 4669,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "vegetable-oil.jpg",
      consistency: "LIQUID",
      name: "vegetable oil",
      nameClean: "vegetable oil",
      original: "Vegetable oil for frying",
      originalName: "Vegetable oil for frying",
      amount: 1,
      unit: "serving",
      meta: ["for frying"],
      measures: {
        us: {
          amount: 1,
          unitShort: "serving",
          unitLong: "serving",
        },
        metric: {
          amount: 1,
          unitShort: "serving",
          unitLong: "serving",
        },
      },
    },
  ],
  readyInMinutes: 45,
  servings: 1,
  instructions:
    "Dredge individual cheese sticks in flour. shake off excess.\nRoll sticks in egg wash,\nThen coat with bread crumbs.\nFry in hot oil for 20 seconds, then flip and fry another 20 seconds.\nServe with Pizza sauce or marinara!!",
  diets: ["lacto ovo vegetarian"],
  dishTypes: [
    "fingerfood",
    "antipasti",
    "starter",
    "snack",
    "appetizer",
    "antipasto",
    "hor d'oeuvre",
  ],
  nutrition: [
    {
      name: "calories",
      count: "709",
    },
    {
      name: "carbs",
      count: "69",
    },
    {
      name: "fat",
      count: "31",
    },
    {
      name: "protein",
      count: "37",
    },
    {
      name: "fiber",
      count: "3",
    },
    {
      name: "potassium",
      count: "192",
    },
  ],
  review: {
    reviews: [
      {
        _id: "648dd6424299c9b57f321d1a",
        userId: "648dcf95c57d691d1b0217e7",
        recipeId: 643809,
        score: 1,
        text: " ВАЫАВЫВ!",
        image: "https://images.apoi.ru/3243fwsf62231",
        userAvatar: "https://images.apoi.ru/1243fsdfd",
        __v: 0,
      },
      {
        _id: "64da3d29c35a474f6a73e484",
        userId: "648dcf95c57d691d1b0217e7",
        recipeId: 643809,
        score: 5,
        text: "hfghfghfg",
        image: "https://images.apoi.ru/3243fwsf62231",
        userAvatar: "https://images.apoi.ru/1243fsdfd",
        __v: 0,
      },
    ],
    averageRating: 2,
  },
};
